export const GAME_CONFIG = Object.freeze({
    INITIAL_HP: 300,
    MATCH_DURATION_SECONDS: 30,
    MATCH_DURATION_FRAMES: 30 * 60,
    SPECIAL_DURATION: 150,
    SAKURA_SPECIAL_DURATION: 150,
    FRAME_RATE: 60,
    NARUTO_SPEED: 4.8,
    SASUKE_SPEED: 5.1,
    SAKURA_SPEED: 4.2,
    PLAYER_RADIUS: 30,
    SAKURA_HEAL_AMOUNT: 4,
    CONTACT_DAMAGE: 3,
    NARUTO_SPECIAL_DAMAGE: 24,
    SASUKE_SPECIAL_DAMAGE: 28
});
